version: "3.8"
services:
  # db:
  #   image: mcr.microsoft.com/mssql/server:2019-latest
  #   environment:
  #     - ACCEPT_EULA=Y
  #     - SA_PASSWORD=MyStrongPassword1234
  #   networks:
  #     - back

  backend:
    build: .
    networks:
      - back
    ports:
      - 5000:80

  frontend:
    build: ./Task4.Client
    depends_on:
      - backend
    ports:
      - 80:8080
    networks:
      - front
  

networks:
  front:
  back: